-- ================================
-- Witrack - Schema Supabase/PostgreSQL
-- Orden de creacion respeta dependencias de foreign keys
-- ================================

-- 1. Sucursales (sin dependencias, debe ir primero)
CREATE TABLE public.branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Tabla de usuarios (depende de branches y auth.users)
CREATE TABLE public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    full_name TEXT,
    role TEXT NOT NULL DEFAULT 'planta' CHECK (role IN ('admin', 'planta', 'sucursal', 'chofer')),
    branch_id BIGINT REFERENCES public.branches(id),
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Trigger para actualizar updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON public.users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 3. Choferes
CREATE TABLE public.drivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rut TEXT UNIQUE NOT NULL,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Camiones
CREATE TABLE public.trucks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL, -- 'carga' o 'descarga'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Programaciones (depende de branches y trucks)
CREATE TABLE public.schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES public.branches(id),
    scheduled_date DATE NOT NULL,
    truck_id BIGINT REFERENCES public.trucks(id),
    status TEXT NOT NULL DEFAULT 'pending',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Envios/Shipments - Flujo principal (depende de trucks, drivers, branches)
CREATE TABLE public.shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id BIGINT NOT NULL REFERENCES public.trucks(id),
    driver_id BIGINT NOT NULL REFERENCES public.drivers(id),
    branch_id BIGINT NOT NULL REFERENCES public.branches(id),

    status TEXT NOT NULL, -- 'esperaIngreso', 'enEspera', 'enCarga', 'cargado', 'despachado', 'recibido', 'incidencia'

    arrival_time TIMESTAMP WITH TIME ZONE,
    load_start TIMESTAMP WITH TIME ZONE,
    load_end TIMESTAMP WITH TIME ZONE,
    dispatch_time TIMESTAMP WITH TIME ZONE,
    reception_time TIMESTAMP WITH TIME ZONE,

    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Fotos de Carga (depende de shipments)
CREATE TABLE public.load_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES public.shipments(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Incidencias (depende de shipments y users)
CREATE TABLE public.incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES public.shipments(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    description TEXT NOT NULL,
    photo_url TEXT,
    status TEXT NOT NULL DEFAULT 'abierta' CHECK (status IN ('abierta', 'en_proceso', 'resuelta')),
    resolution TEXT,
    reported_by UUID REFERENCES public.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    resolved_at TIMESTAMP WITH TIME ZONE
);

-- 9. Historial de cambios de estado - Auditoria (depende de shipments y users)
CREATE TABLE public.shipment_status_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES public.shipments(id) ON DELETE CASCADE,
    old_status TEXT,
    new_status TEXT NOT NULL,
    changed_by UUID REFERENCES public.users(id),
    notes TEXT,
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ================================
-- INDICES
-- ================================
CREATE INDEX idx_shipments_status ON public.shipments(status);
CREATE INDEX idx_shipments_branch ON public.shipments(branch_id);
CREATE INDEX idx_shipments_truck ON public.shipments(truck_id);
CREATE INDEX idx_shipments_created ON public.shipments(created_at);
CREATE INDEX idx_trucks_plate ON public.trucks(plate);
CREATE INDEX idx_drivers_rut ON public.drivers(rut);
CREATE INDEX idx_schedules_date ON public.schedules(scheduled_date);
CREATE INDEX idx_schedules_branch ON public.schedules(branch_id);
CREATE INDEX idx_status_log_shipment ON public.shipment_status_log(shipment_id);
CREATE INDEX idx_incidents_status ON public.incidents(status);
CREATE INDEX idx_incidents_shipment ON public.incidents(shipment_id);
CREATE INDEX idx_load_photos_shipment ON public.load_photos(shipment_id);

-- ================================
-- DATOS INICIALES (Seed)
-- ================================
INSERT INTO public.branches (name, code) VALUES
('Sucursal Central', 'CENTRAL'),
('Sucursal Norte', 'NORTE'),
('Sucursal Sur', 'SUR');

-- ================================
-- ROW LEVEL SECURITY (RLS)
-- ================================

-- Habilitar RLS en todas las tablas
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trucks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.load_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipment_status_log ENABLE ROW LEVEL SECURITY;

-- Users: pueden ver/editar su propio perfil
CREATE POLICY "Users can view own profile" ON public.users
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.users
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Enable insert for authenticated users" ON public.users
    FOR INSERT WITH CHECK (auth.uid() = id);

-- Admin puede ver todos los usuarios
CREATE POLICY "Admins can view all users" ON public.users
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.users u
            WHERE u.id = auth.uid() AND u.role = 'admin'
        )
    );

-- Branches: lectura para todos los autenticados, escritura para admins
CREATE POLICY "Authenticated users can view branches" ON public.branches
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can insert branches" ON public.branches
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update branches" ON public.branches
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Drivers, Trucks, Schedules, Shipments, etc: acceso completo para autenticados
CREATE POLICY "Authenticated users full access" ON public.drivers
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users full access" ON public.trucks
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users full access" ON public.schedules
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users full access" ON public.shipments
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users full access" ON public.load_photos
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users full access" ON public.incidents
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users full access" ON public.shipment_status_log
    FOR ALL USING (auth.role() = 'authenticated');

-- ================================
-- STORAGE BUCKET
-- ================================
-- Crear bucket para fotos (ejecutar en SQL Editor de Supabase)
INSERT INTO storage.buckets (id, name, public) VALUES ('load-photos', 'load-photos', true);

-- Politicas de storage: autenticados pueden subir, todos pueden ver
CREATE POLICY "Authenticated users can upload photos" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'load-photos' AND auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update photos" ON storage.objects
    FOR UPDATE USING (bucket_id = 'load-photos' AND auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete photos" ON storage.objects
    FOR DELETE USING (bucket_id = 'load-photos' AND auth.role() = 'authenticated');

CREATE POLICY "Anyone can view photos" ON storage.objects
    FOR SELECT USING (bucket_id = 'load-photos');
