-- Tablas principales para Truck Management App (Supabase/PostgreSQL)

-- 0. Tabla de usuarios (vinculada a Supabase Auth)
CREATE TABLE public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    full_name TEXT,
    role TEXT NOT NULL DEFAULT 'planta' CHECK (role IN ('admin', 'planta', 'sucursal', 'chofer')),
    branch_id BIGINT REFERENCES public.branches(id),
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Trigger para actualizar updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at 
    BEFORE UPDATE ON public.users 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 1. Sucursales
CREATE TABLE public.branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Choferes
CREATE TABLE public.drivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rut TEXT UNIQUE NOT NULL,
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Camiones
CREATE TABLE public.trucks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate TEXT UNIQUE NOT NULL,
    type TEXT NOT NULL, -- 'carga' o 'descarga'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Programaciones (Schedules)
CREATE TABLE public.schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES public.branches(id),
    scheduled_date DATE NOT NULL,
    truck_id BIGINT REFERENCES public.trucks(id),
    status TEXT NOT NULL DEFAULT 'pending',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Envíos (Shipments) - Flujo principal
CREATE TABLE public.shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id BIGINT NOT NULL REFERENCES public.trucks(id),
    driver_id BIGINT NOT NULL REFERENCES public.drivers(id),
    branch_id BIGINT NOT NULL REFERENCES public.branches(id),
    
    status TEXT NOT NULL, -- 'esperaIngreso', 'enEspera', etc.
    
    arrival_time TIMESTAMP WITH TIME ZONE,
    load_start TIMESTAMP WITH TIME ZONE,
    load_end TIMESTAMP WITH TIME ZONE,
    dispatch_time TIMESTAMP WITH TIME ZONE,
    reception_time TIMESTAMP WITH TIME ZONE,
    
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Fotos de Carga
CREATE TABLE public.load_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES public.shipments(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL, 
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Incidencias
CREATE TABLE public.incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES public.shipments(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    description TEXT NOT NULL,
    photo_url TEXT,
    status TEXT NOT NULL DEFAULT 'abierta' CHECK (status IN ('abierta', 'en_proceso', 'resuelta')),
    resolution TEXT,
    reported_by UUID REFERENCES public.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    resolved_at TIMESTAMP WITH TIME ZONE
);

-- 8. Historial de cambios de estado (auditoría)
CREATE TABLE public.shipment_status_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id BIGINT NOT NULL REFERENCES public.shipments(id) ON DELETE CASCADE,
    old_status TEXT,
    new_status TEXT NOT NULL,
    changed_by UUID REFERENCES public.users(id),
    notes TEXT,
    changed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Índices para optimización
CREATE INDEX idx_shipments_status ON public.shipments(status);
CREATE INDEX idx_shipments_branch ON public.shipments(branch_id);
CREATE INDEX idx_trucks_plate ON public.trucks(plate);
CREATE INDEX idx_status_log_shipment ON public.shipment_status_log(shipment_id);
CREATE INDEX idx_incidents_status ON public.incidents(status);
CREATE INDEX idx_incidents_shipment ON public.incidents(shipment_id);

-- Datos iniciales (Seed)
INSERT INTO public.branches (name, code) VALUES 
('Sucursal Central', 'CENTRAL'),
('Sucursal Norte', 'NORTE'),
('Sucursal Sur', 'SUR');

-- ================================
-- ROW LEVEL SECURITY (RLS)
-- ================================

-- Habilitar RLS en todas las tablas
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trucks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.load_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipment_status_log ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso (usuarios autenticados pueden leer/escribir)
-- Ajustar según necesidades de seguridad

-- Users: pueden ver su propio perfil, admin puede ver todos
CREATE POLICY "Users can view own profile" ON public.users
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" ON public.users
    FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Enable insert for authenticated users" ON public.users
    FOR INSERT WITH CHECK (auth.uid() = id);

-- Branches: todos pueden ver
-- Branches: Lectura pública, Gestión solo admins
CREATE POLICY "Anyone can view branches" ON public.branches
    FOR SELECT USING (true);

CREATE POLICY "Admins can manage branches" ON public.branches
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.users
            WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- Drivers, Trucks, Schedules, Shipments: usuarios autenticados tienen acceso completo
CREATE POLICY "Authenticated users full access" ON public.drivers
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users full access" ON public.trucks
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users full access" ON public.schedules
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users full access" ON public.shipments
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users full access" ON public.load_photos
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users full access" ON public.incidents
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users full access" ON public.shipment_status_log
    FOR ALL USING (auth.role() = 'authenticated');

-- ================================
-- STORAGE BUCKET
-- ================================
-- Ejecutar en Supabase SQL Editor o crear desde la UI:
-- INSERT INTO storage.buckets (id, name, public) VALUES ('load-photos', 'load-photos', true);

-- Política para el bucket de fotos
-- CREATE POLICY "Authenticated users can upload photos" ON storage.objects
--     FOR INSERT WITH CHECK (bucket_id = 'load-photos' AND auth.role() = 'authenticated');

-- CREATE POLICY "Anyone can view photos" ON storage.objects
--     FOR SELECT USING (bucket_id = 'load-photos');
